paulgibbs/behat-wordpress-extension

src/WpcliLogger.php
=> WP-CLI: use `sed` instead of `xxd` with OpenSSL to verify Shouty Logger checksum

bin/travis/default-site.tpl.conf
Fixes nginx server not correctly set up on local copies.
=> Use ROOT placeholder rather than hard-coded path.

docs/settings.md
s/siteurl/site_url
Very simple typo fix I noticed in the settings page's example YML file,
=> typo fix in settings page's YML

docs/settings.md, src/ServiceContainer/WordpressBehatExtension.php
When the `site_url` is not present in `behat.yml`, default to `mink.base_url`.
If a `site_url` is not provided in the config then accessing `wp-admin/` or `wp-login.php` won't work: https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/Context/RawWordpressContext.php#L53. A `site_url` is necessary when WordPress is not installed at the `base_url`, but otherwise we can just default to `base_url` so that the URL need not be duplicated in the `behat.yml`.
Manually inspected. It will be covered by the test suite in a forthcoming PR.
=> If site_url is not present, default to mink's base_url

.travis.yml, bin/travis/deploy-key.sh
Move script for preparing the publish key to its own file and wrap it inside a conditional in `.travis.yml`
The builds are failing on my copy as I don't have the decryption key.
It hasn't, I can't :)
=> Only decrypt publish-key when we are publishing to gh-pages

src/Driver/WpcliDriver.php
If the path to the SQL file to import begins with a directory separator or `~` it should be treated as an absolute path.
Fixes #56
To allow absolute file paths to be provided. This allows developers to read it from the `behat.yml`, using placeholders such as `%paths.base%` (which resolves to absolute paths).
It also makes importing a database possible when the WordPress install is hosted remotely. In that instance, the SQL dump is (often) on the remote machine, and not on the local machine.
Yes, this patch is in use as part of a client project.
(There is actually a partial breaking change, if a relative path was provided with a leading directory separator. I'm not sure if such a file would have been successfully imported0.
=> Support absolute paths to SQL dumps

phpcs-ruleset.xml, src/Driver/WpapiDriver.php
This PR adds more PHPCS rules to our existing ruleset. These add to the generic rules loaded by the PSR1 and PSR2 extensions. These new rules were taking from a review of the sniffs configured in the https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards project, and mostly try to prevent creative mis-use of certain PHP elements in edge cases.
Stops us having to code review trivial stuff.
Ran it locally. It found one problem in the existing code base, which I fixed (via `phpcbf`, though I'm not sure if we want to auto-run that -- probably not).
=> Add more PHPCS rules.

composer.json, composer.lock
This PR loosens the version constraints on composer dependencies by altering the operator on `behat/behat` and removing direct references to packages that are require implicitly through other dependencies.
Related to https://github.com/paulgibbs/behat-wordpress-extension/issues/66
Loosening these requirements makes it more likely that WordHat can be installed on projects with diverse dependencies. Currently WordHat can only be used on projects using Behat 3.1.x and Symfony 2. Many projects have moved on to Symfony 3 and Behat itself supports 2 or 3. WordHat is restricted to Symfony 2, perhaps unnecessarily.
I have tested this change only so far as getting WordHat to install using the branch in this pull request. See the notes in https://github.com/paulgibbs/behat-wordpress-extension/issues …
=> Composer requirements

docs/installation.md
The `--dev` flag should be added to the composer installation instructions so the library is only installed as a development dependency.
(Previous PR was incorrect. Yay for testing.)
=> Installation instructions: Install as a development dependency

src/Context/RawWordpressContext.php
Try to fix a bug with Behat entering both user/password into username field
by explicitly setting focus on the fields before entering values.
See #47
Tested only on Travis-CI (where we've been able to recreate the bug semi-reliably).
=> Rework `login()` method

features/login.feature, features/toolbar.feature, src/Context/PageObjectContextTrait.php, src/Context/RawWordpressContext.php, src/Context/WordpressContext.php, src/PageObject/Element/Toolbar.php
1. Adds a Toolbar object which makes defining steps involving interacting with the toolbar easier
2. Adds a `PageObjectContextTrait` which makes it easier for Contexts to create page/element objects.
3. Fixes the log-out step for JS-enabled drivers
4. Fixes the log-in step for Goutte driver
5. Adds tests
The `PageObjectContextTrait` means that classes that can't extend from `PageObjectContext` can still implement `PageObjectAwareContext` without having to actually duplicate the code.
Fixes #65  
(Also fixes bug introduced in #68).
The Toolbar encapsulates the WordPress toolbar and exposes an API for interacting with it. This makes steps interacting with it easier and simpler. 
It allows to fix #65 by using it's `logOut()` method. 
Yes: …
=> Adds Toolbar object

composer.json, composer.lock
Updating the composer.lock file in a PHP 7 environment is causing
composer to pick `ocramius/proxy-manager` v2 (requires PHP >= 7) over v1.
Thus the `composer.lock` is locking us to dependencies that cannot run in
a PHP 5.6 environment. In particular on Travis, the PHP 5.6 builds are failing.
See https://wordhat.slack.com/archives/general/p1489679724921137
Related: #77
Composer will by default use the PHP version it is running in when updating the `.lock` file, and will choose dependency versions accordingly. We are telling composer to consider itself running in PHP 5.6, thus it will ignore dependancy paths that require PHP > 5.6. 
Ensures that the `composer.lock` is compatible with PHP 5.6. 
Alternatives would be to:
- Remove PHP 5.6 tests
- Pin upstream packages to specific versions
- …
=> Set PHP platform to minimum required version.

src/Context/WordpressContext.php
Rather than having the toolbar fixed to the top of the viewport, where it can potentially cover elements which we want to interact with, we position it at the top of the page.
#81
When using the Selenium driver, elements underneath the toolbar cannot be interacted with. Instead, Selenium errors with something similar to:
> Element is not clickable at point (577.0999755859375, 8.75). Other element would receive the click: <div id="wpadminbar" class=""></div>
Yes, locally and on Travis.
See #81.
=> Fix Links / Buttons behind the wp-admin bar are inaccessible

src/Context/RawWordpressContext.php, src/Driver/Element/Wpapi/ContentElement.php, src/Driver/Element/Wpcli/ContentElement.php
The driver re-organisation left the base Context using the backwards-compatible methods to test that they worked. This change updates those methods to use the new interfaces directly.
The backpat methods are planned to be removed in 1.0.0 and getting them out early helps us test more directly against those new interfaces as we build to feature completion.
Tested locally.
=> Drivers: update base Context methods to use new Driver interface.

features/readme.feature
Intended for debugging, no longer required. See #83
=> Feature: remove `readme` feature.

src/Driver/WpcliDriver.php
We require WP Cli >= 0.24.0, but the current regex for extracting the version is too strict. It expects three single digits separated by full stops.
This breaks if you're running an alpha version and will break if/when WP-Cli
reaches double digits in version number. E.g  
```
wp --version
WP-CLI 1.2.0-alpha-9fda2a7
./vendor/bin/behat
╳ Your WP-CLI is too old; version 0.24.0 or newer is required. (RuntimeException)
```
This PR changes the regex to accept any string (after the WP CLI text) and passes it to `version_compare()`. That function is pretty good at handling anything you can throw at it. I wrote a quick script to check how it will handle various inputs, here are the results:
```
0.23.0-beta-1ekjfsaf	 ✗
0.24.1-alpha-13ga4	 ✓
0.24.0-alpha-13rab	 ✗
Im not a version	 ✗
0.24.0	 ✓
1	 ✓
✓ …
```
=> Fix strict WP-Cli version requirement.

src/Context/RawWordpressContext.php
For unknown reasons, Behat/Mink seems to have problems logging into WordPress on an occassional and intermittent basis. A common failure is that Mink does not enter the username or password into the correct elements on the log-in form, or leaves one blank.
We've iterated fixes several times -- some environment specific, e.g. Travis-CI -- and this commit spins the wheel once more.
My local testing, and on Travis-CI, suggests this change improves the reliability of entering data into the log-in form. The idea is clearing the field values prior to data entry works around some sort of quirk in WebDriver/Selenium.
See #47.
=> Try improvements to the log-in step.

features/toolbar.feature
This should not be required; the `WordPressContext`'s `resetBrowser()` instructs Mink to soft-reset the browser (clear cookies, etc).
My testing suggests this is no longer required as long as the `WordPressContext` is specified in `behat.yml`, which is our recommendation.
Local and on Travis-CI.
=> Features: remove `insulated` keyword from all tests.

features/toolbar.feature, features/user.feature
Our previous approach to "which tests have to run with JS" was not formally defined and was basically "use it where it helps make the tests more realistic". I agree to a point, but we need to be more specific.
For tests that touch the Toolbar, given the hacks we have to do to support it already, let's have those always use javascript. Ditto for anything known trouble areas, like User authentication.
We were pretty much doing this already; this PR just changes the syntax a little bit, and removes javascript from one test.
Non-JS tests are faster.
Locally.
=> Tweak which tests can use the `javascript` tag or not.

.travis.yml, bin/travis/behat.yml, features/widget.feature, src/Context/WidgetContext.php, src/Driver/Element/Wpapi/WidgetElement.php, src/Driver/Element/Wpcli/WidgetElement.php, src/Driver/WpcliDriver.php, src/ServiceContainer/config/drivers/wpapi.yml, src/ServiceContainer/config/drivers/wpcli.yml
Defines a step for adding a widget to a sidebar, e.g.
> Given I have the "RSS" widget in "Widget Area"
> | Title   | Url                              | Items   |
> | My feed | https://wordpress.org/news/feed/ | 3       
Adds a new element for the WP-Cli and WP API drivers to support this step.
It also adds `export WP_CLI_STRICT_ARGS_MODE=1` to the set up. In WP-Cli 'strict' mode allows you to use the `--url` argument multiple times. By default `--url` is a global parameter that refers to the site URL, but it may also be an argument to the command being run (see`widget.feature` for an example). 
Strict mode allows you to distinguish between the two: `--url` before the command refers to the [global parameter](https://make.wordpress.org/cli/handbook/config/#global-parameters) and `--url` …
=> Add a step for adding a widget to a sidebar

features/login.feature, src/Context/UserContext.php
Do not use multiple "givens" in a single scenario in the log-in feature.
These scenarios are a little unusual because we are testing the log-out flow, but I don't think it looks right to have multiple givens to set state. Further more, while "I am an anonymous user" does log you out, it was clearer to replace it with something that explicitly said "I log out".
Clarity.
Locally.
=> Features, Log-in: do not use multiple "givens" in a single scenario.

src/Context/WordpressContext.php
In a javascript scenario (when using Selenium) we run a @BeforeStep hook to address the issue of the admin toolbar hiding elements (and thus potentially making them unclickable). 
If a browser window is not open, then `Selenium2Driver::executeScript()` will throw an 'unknown'. This typically happens when there are no background steps which open a browser window (the `@BeforeStep` does not run for them.
Obviously, in such situations this workaround is not required (it's only an issue when we are interacting with the page via the browser.). So the solution is to catch the exception and let it fail silently.
My test are currently failing for no good reason :)
Yes, via tests written for clients
=> @BeforeStep throws exception on initial step in @javascript scenario

.travis.yml
Disable Travis-CI `pip` caching.
We use Mkdocs to build the website with its Material theme.
Disabling Python caching will ensure we always build the website with the latest version of the template.
Previously I was occasionally clearing Travis-CI's cache manually to prevent this.
Not at all.
=> CI: disable Travis-CI `pip` caching.

src/Driver/WpcliDriver.php
See #112 for details
Allow users to know the issue is WordPress core not being installed rather than wpcli not finding the WordPress core files.
=> Friendlier error message when WordPress core is not installed

src/Driver/WpcliDriver.php
wpcli sometimes sends warnings, such as `"Plugin '{$plugin->name}' is already active."`, to `stderr`. WordHat should not fail in these instances. Instead we should rely on wpcli returning an exit code greater than zero when there are legitimate errors.
See #111 
Custom tests making use of WordHat are failing when using the wpcli driver and wpcli returns warning messages to `stderr`. Ideally the warnings would be shown yet the WordHat tests would still pass.
Tested against tests activating plugins that are already active.
=> Don't fail WordHat tests when wpcli returns stderr output

src/Driver/Element/Wpcli/UserElement.php
=> Drivers, WP-CLI, Users: when fetching, request all available properties.

src/Driver/Element/Wpcli/ContentElement.php
Multiple terms can now be added by being delimited with a comma.
If you want to add a term that contains a comma, wrap the phrase with " characters.
Fixes #135 better.
=> Drivers, WP-CLI: Improve creating content with terms.

src/PageObject/DashboardPage.php
Per title. The value we were comparing against was in English, which is limiting if we support multilingual step definitions in the future.
I'd rather have the code written flexibly and solve the step definition translation puzzle later.
#132 
Locally against existing test suite, which covers the changed method.
=> Contexts, Dashboard: change "I am on the dashboard" step to check URL.

src/Context/Traits/ContentAwareContextTrait.php, src/Driver/Element/Wpcli/ContentElement.php, src/Driver/Element/Wpphp/ContentElement.php
Drivers, WP-PHP: remove `get_permalink()` wrapper and pass the post by object, not ID.
Performance optimisation and tidy-up of single-use function.
Locally.
=> Drivers, WP-PHP: remove `get_permalink()` wrapper.

src/Context/DashboardContext.php, src/Context/WordpressContext.php
`DashboardContext`, also, now receives a `DashboardPage` object rather than a `AdminPage` object.
This seems a better location than the common `WordpressContext`.
This again seems a more appropriate object to use rather than the generic `AdminPage` object.
Locally.
=> Move "open the dashboard" step into the Dashboard context.

.travis.yml
Tweaks caching.
Disables JS tests.
Travis-CI changed something about ~10 days ago and it broke something to do with the communication between Selenium and the web browser. The error message is vague, unhelpful, and there's at least two separate packages between Selenium and the web browser, and trying to debug both will take a huge amount of time.
Because I'd rather have the build badges fail when there's a failure with the tests, not because of Travis-CI.
In branches.
=> Selenium tweaks

src/Context/UserContext.php
Fix inconsistency in iAmViewingAuthorArchive context.
* See https://github.com/paulgibbs/behat-wordpress-extension/issues/183
* https://github.com/paulgibbs/behat-wordpress-extension/issues/183
Trying to make tests consistent.
I have run all tests and they are passing, but extra testing may be needed.
=> Use user role instead of name in iAmViewingAuthorArchive context

docs/configuration/settings.md, src/Driver/WpcliDriver.php, src/Driver/WpphpDriver.php, src/ServiceContainer/WordpressBehatExtension.php, src/ServiceContainer/config/drivers/wpcli.yml
To facilitate environments where the WordPress path is not known until runtime, and where CLI-over-SSH is used, the `path` argument is now optional.
I am not sure why `path` used to be checked with `realpath()`; it was implemented in the earliest stagest of WordHat's development, and it might not have had a reason that stands up to scrutiny at the current time.
See #185
=> Drivers: set `path` argument as optional.

docs/recipes/faq.md, mkdocs.yml, src/Compiler/DriverElementPass.php, src/Compiler/EventSubscriberPass.php, src/Context/RawWordpressContext.php, src/Listener/DriverListener.php, src/ServiceContainer/WordpressBehatExtension.php, src/ServiceContainer/config/services.yml, src/WordpressDriverManager.php
Support use of multiple drivers. Why? Why not.
For #189
Supports use of multiple drivers concurrently. This is very edge-case at the moment, but there's a lot of implementation we can lift from the Drupal Behat Extension -- which was always the intention -- and it might be helpful in the future if/when we introduce a REST API driver. Or if people build custom drivers. Or other weird edge cases.
Locally.
None of the standard tests have been modified to demonstrate the driver switching because that will be a serious pain to get working on the CI environments. I'm thinking about calling this an "experimental" feature in the docs until such time someone finds a good use case for this, and helps us have confidence in the feature.
=> Support for multiple drivers

src/Driver/Element/Wpphp/DatabaseElement.php, src/Driver/WpcliDriver.php
Improves display of error messages, especially for WP-CLI.
#197
=> Drivers: if a failure, print stderror if stdout is empty.

.travis.yml, appveyor.yml, composer.json, composer.lock
Update Composer because Composer, and to try fix #202
Require PHP 7.1 to resolve upstream dependencies aggressively requiring more recent versions of PHP.
Loosely related to #202
Locally, but testing on Travis-CI is important for our PHP version support.
=> Update Composer - require PHP 7.1

docs/changelog.md, src/Context/Traits/UserAwareContextTrait.php, src/Driver/Element/Wpcli/UserElement.php, src/Driver/Element/Wpphp/UserElement.php
Remove `validateCredentials` methods in `UserElement` classes. This attempted to compare passwords on user objects.
Methods will be removed in 4.0.0.
See #155
I've decided I do not like behaviour that cannot be specific to all drivers, unless there is a strong reason, and I do not think this has it. I have been skeptical of the benefit of trying to compare user passwords in this method, so I am going to rip it out.
Not locally. :D
=> Context, User: deprecate `validateCredentials` in `UserElement` classes.

src/Driver/Element/Wpcli/ContentElement.php, src/Driver/Element/Wpphp/ContentElement.php
This prevents the underlying `WP_Query` in WP-PHP driver and WP-CLI itself
returning sticky posts when retriving a post ID by post title, as seen with
the "I am on the edit screen for" step definition.
This does not affect intentionally retrieving sticky posts in this way.
Fixes #218
Tested locally.
=> Drivers, Content: ignore sticky posts when fetching.

src/Context/Traits/UserAwareContextTrait.php, src/Context/UserContext.php, src/PageObject/LoginPage.php
* Add a `LoginPage` `Page` object to interact with the WordPress login page.
* Refactor `UserAwareContextTrait` to use the new `LoginPage` object
Inconsistent user authentication. See [this Slack thread](https://wordhat.slack.com/archives/C472TKN79/p1550278140001300).
When writing tests using WordHat I found any scenarios requiring user authentication to be very inconsistent. The tests would fail on one run and pass on the next.
This is an attempt to get my work done in https://github.com/pantheon-systems/example-wordpress-composer/pull/79 merged back upstream in WordHat.
Tests with authentication using these updates, specifically filling fields with JavaScript, have passed with the wp-cli driver locally in a Docker instance, on CircleCI and on GitLab. Previously, the tests would fail …
=> Add login page object

src/Context/Traits/UserAwareContextTrait.php
Catch exception in `logOut()` method.
See #232
=> Context, Users: `logOut` can fail if used in first line of step definitions

src/Context/Traits/UserAwareContextTrait.php
A further fix at stopping log-out related exceptions and errors when
"I am an anonymous user" is used early in a feature test.
=> Context, Users: only log out if the user is currently authenticated.

docs/recipes/faq.md
The link at the bottom of [the Support tab on WordHat.info](https://wordhat.info/recipes/faq.html) points to an incorrect URL. It should point to settings.html instead of settings.md.
=> Fix a documentation link

src/Driver/Element/Wpphp/UserElement.php
When using the `wpphp` driver, creating users triggers an error because the `UserElement::create()` method doesn't pass the correct variable to its `get()` method after creating the user.
This fixes that.
=> Fix usage of an undefined variable when attempting to create users with the wpphp driver

.github/ISSUE_TEMPLATE/---report-a-bug.md, .github/ISSUE_TEMPLATE/---request-a-feature.md, .travis.yml, composer.json, composer.lock, docs/getting-started/installation.md
Bump minimum PHP requirements from 7.1 to 7.2
#256
On CI only as I am not aware of any backwards incompatible changes in the WordHat codebase for a PHP 7.1 to 7.2 migration.
=> Bump minimum PHP requirements from 7.1 to 7.2
