- composer.json
- composer.lock
> Add `sensiolabs/behat-page-object-extension` to Composer requirements.

- src/Driver/WpcliDriver.php
Throw an exception if we have a non-empty stderror or non-zero exit code.
Otherwise return only the stdout and exit code.
Previously stdout and stderror were merged into one variable. So if
anything were output by WP-Cli (to either stderror or stdout) then
we would throw an UnexpectedValueException.
> Use proc_open so that we can retrieve stdout and stderror separately

- docs/faq.md
- docs/settings.md
> Docs: update for `wpcli.binary` option.

- src/Driver/WpapiDriver.php
> Drivers, WP-API: de-duplicate plugin function loading code.

- docs/changelog.md
- mkdocs.yml
Add Change Log to website.
Try to communicate better with casually-interested developers about progress in WordHat, and help grow the perception that the project has perception.
Locally via `mkdocs serve`.
> Add Change Log.

- src/Context/DebugContext.php
> Add DebugContext

- features/viewing-blog-posts.feature
- src/Context/ContentContext.php
- src/Driver/BaseDriver.php
- src/Driver/DriverInterface.php
- src/Driver/WpapiDriver.php
- src/Driver/WpcliDriver.php
See #60
See #60
See #60
Yes: https://travis-ci.org/stephenharris/behat-wordpress-extension/builds/206936735 - The failed build was due to #47
> Fix "I am viewing post" step

- composer.json
- composer.lock
- docs/installation.md
> Move Goutte and Selenium to Composer dev-dependencies, and update docs.

- docs/stylesheets/style.css
- docs/theme/partials/header.html
- docs/theme/partials/search.html
- docs/theme/partials/social.html
I ran the https://www.deque.com/products/axe/ tool and fixed a few of the quicker-to-fix accessibility warnings the tool raised.
Because not everyone uses the internet in the same way.
Local testing with the aXe plugin for Chrome.
> Website a11n tweaks.

- src/Driver/Element/Wpapi/CacheElement.php
- src/Driver/WpapiDriver.php
Fix bugs in WP-API introduced in recent driver refactoring.
No, because we haven't written scenarios that use these methods (yet).
> Fix mistakes in WP-API driver

- src/PageObject/Element/Toolbar.php
> Toolbar PageObject: fix calls to `evaluateScript`.

- features/toolbar.feature
Latter does not work if WP is not at the root of the site.
> Toolbar feature: use `I am on the homepage` instead of `I am on "/"`.

- src/ServiceContainer/config/services.yml
Because the delete key is always the most productive.
Simplifying the `services.yml`
Cleaning up the `services.yml` makes it easier to read.
Locally
> Tidying up the services.yml

- docs/drivers.md
- src/Driver/WpapiDriver.php
- src/ServiceContainer/WordpressBehatExtension.php
> Rename "API" driver to "PHP"

- .gitignore
- .travis.yml
- bin/travis/behat.yml
- bin/travis/selenium.sh
- composer.json
- composer.lock
> Travis-CI: changes to Selenium (and web drivers).

- .travis.yml
- composer.json
- composer.lock
- docs/getting-started/installation.md
> Require PHP 7.

- src/Driver/Element/Wpphp/PluginElement.php
> Drivers, WP-PHP: fix deactivating plugins.

- src/Context/DashboardContext.php
- src/Context/EditPostContext.php
- src/Context/RawWordpressContext.php
- src/Context/Traits/DatabaseAwareContextTrait.php
> 1.0 deprecations

- features/dashboard.feature
- features/user-admin.feature
- src/Context/EditPostContext.php
- src/Context/UserContext.php
- src/Driver/Element/Wpphp/UserElement.php
Add tests for deleting users.
Plus some related refactoring and jiggling of things.
#149
Locally.
> Add tests for deleting users.

- features/plugin.feature
- features/theme.feature
- src/Context/SiteContext.php
Add tests for Plugins and Themes
#149
Test coverage so we know the driver works.:)
Locally.
> Add tests for Plugins and Themes

- src/Driver/WpcliDriver.php
Add logging if a fail happens.
> WP-CLI driver improvements

- src/ServiceContainer/config/services.yml
> Quote value starting with % to validate YML

- .editorconfig
- composer.json
- composer.lock
- phpstan.neon
- src/Context/ContentContext.php
- src/Context/EditPostContext.php
- src/Context/ToolbarContext.php
- src/Driver/BaseDriver.php
> Add PHPStan

- .travis.yml
- appveyor.yml
- src/ServiceContainer/config/drivers/blackbox.yml
- src/ServiceContainer/config/drivers/wpcli.yml
- src/ServiceContainer/config/drivers/wpphp.yml
Validate yml files to allow Behat to run in strict mode without errors. Addresses #166
> Validate yml

- features/editing-content.feature
- src/Context/EditPostContext.php
Tests for Edit Post context
For #149
> #149 Tests for Edit Post context

- src/Context/EditPostContext.php
- src/PageObject/AdminPage.php
- src/PageObject/Element/AdminMenu.php
Tidy up PHPDoc, comments, and untested method in AdminMenu PageObject. See 8246b95.
For #149
> PageObjects review for #149

- features/authentication.feature
- features/dashboard.feature
- features/editing-content.feature
- features/navigation.feature
- features/plugin.feature
- features/theme.feature
- features/toolbar.feature
- features/user-admin.feature
- features/viewing-content.feature
- features/widget.feature
Add story syntax to feature files.
Each feature file in Behat needs to explain what the feature is at the top of the file. Previously this was just discerned from the filename, but let's do it more properly.
No affect.
> Features: add story syntax.

- src/Context/Traits/UserAwareContextTrait.php
Pull request that includes fix for the log in step.
* https://github.com/paulgibbs/behat-wordpress-extension/issues/47
Some log in steps occasionally falling. This is inconsistent behavior. Proposed fix looks to resolve a problem.
I have run test suite several times.
> Fix setting value in log in step

- docs/robots.txt
> Add robots.txt

- src/Context/Traits/UserAwareContextTrait.php
Brought in from Drupal Extension: https://github.com/jhedstrom/drupalextension/pull/379
See #201
I'm hoping this might help address #47
> Fix null session when first step asserts a login

- build.xml
- build/docker/docker-entrypoint.sh
- build/templates/docker-compose.yml.template
The travis build (for wpcli) was failing owing to an uncontrolled mysql upgrade.
MySQL was brought to the latest version automatically by the build process. This caused wpcli to be unable to connect to mysql as the the client libraries in the latest php image are out of date.
> Fix travis build

- features/theme.feature
Perhaps this was left over from a copy/paste?
> Replace plugin with theme

- src/PageObject/Element/Toolbar.php
> Swap jQuery for plain Javascript.

- composer.json
- composer.lock
Removes following unused Composer packages:
- `joomla-projects/selenium-server-standalone`
- `phing/phing`
Tidy-up.
Travis-CI.
- [] I have added tests to cover my changes.
> Composer: remove unused packages.

- .gitignore
- composer.json
- wp-cli.yml
First pass at standardising project development local setup.
After recent changes for Travis-CI, for local dev, I'd like to invoke Behat through Composer, and share as much as of the config as possible.
There will be more to do here, including docs, but it's primarily to make things easier for me to set up the project on different machines for development.
Local.
> CI: first pass at standardising project development local setup.

- .travis.yml
- behat.yml
- composer.json
- composer.lock
Re-add tests to CI running with both the WP-PHP and WP-CLI drivers.
Matches what we used to have before I pulled it out out. Gives us reliability that a change works for all core drivers.
Travis-CI
> CI: test both WP-PHP and WP-CLI drivers

- src/Context/RawWordpressContext.php
- src/Context/Traits/UserAwareContextTrait.php
- src/Context/WordpressContext.php
- src/PageObject/LoginPage.php
This PR covers a range of issues wherein a user is either not able to log in due to a Selenium error, or appears to be logged-out during the subsequent test run.
#245 - for the "remember me" checkbox.
#47 - for general log-in failures.
Makes the software reliable and developers less angry.
Locally. Against the core project tests, and against a client project's tests.
Against the core project tests, I ran a loop of tests for 30 minutes, and several hundred log-ins later, I had no failures. I'd have expected at least one failure based on previous experience.
> [245] User authentication improvements

- .editorconfig
- i18n/template.xliff
- scripts/extract-translations.sh
- src/Context/RawWordpressContext.php
Add support for translations.
#206
To allow end-user to translate our step definitions for use in their local language. I've written a rudimentary strict to try to automate building of the base `xliff` file.
I don't know how to validate the output or test the `template.xliff` so that will have to wait for user testing/bug reports.
> [206] Add support for translations.
